services:

  # otel-tui:
  #   image: ymtdzzz/otel-tui:latest
  #   container_name: otel-tui
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "4317:4317"
  #     - "4318:4318"
  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--name nats --http_port 8222 --js"
    networks: ["nats"]

  nats_stream_creator:
    image: synadia/nats-server:nightly
    depends_on:
      - nats
    entrypoint:
      [
        "sh",
        "-c",
        "until nats --server=nats:4222 stream create payments --subjects 'payment.process' --storage memory
        --replicas 1 --retention=limits --discard=old --max-msgs 100000 --max-msgs-per-subject 10000
        --max-bytes 1294967296 --max-age 1d --max-msg-size 10485760 --dupe-window 2m --allow-rollup
        --no-deny-delete --no-deny-purge; do sleep 1; done",
      ]
    networks: ["nats"]

networks:
  nats:
    name: nats
